<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daftar Peminjaman</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        .header {
            text-align: center;
            margin-top: 20px;
        }

        .header img {
            width: 100px;
            height: auto;
            display: block;
            margin: 0 auto 10px auto;
        }

        .header h1 {
            font-size: 28px;
            margin: 10px 0;
        }

        h2 {
            text-align: center;
            font-size: 20px;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        table th,
        table td {
            border: 1px solid #000;
            padding: 10px;
            text-align: center;
            font-size: 14px;
        }

        table th {
            background-color: #f4f4f4;
            font-weight: bold;
        }

        table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            text-align: center;
            font-size: 12px;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="header">
        <!-- Pastikan path logo sudah benar -->
        <img src="{{ public_path('images/logo.png') }}" alt="Logo Eduventory" width="30%">
    </div>

    <h2>Daftar Peminjaman</h2>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Barang</th>
                <th>Nama Peminjam</th>
                <th>Jumlah</th>
                <th>Tanggal Peminjaman</th>
                <th>Tanggal Pengembalian</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($peminjaman as $index => $item)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $item->barang->nama_barang_222291 ?? 'Barang Tidak Ditemukan' }}</td>
                    <td>{{ $item->nama_peminjam_222291 }}</td>
                    <td>{{ $item->jumlah_222291 }}</td>
                    <td>{{ $item->tanggal_peminjaman_222291 }}</td>
                    <td>{{ $item->tanggal_pengembalian_222291 }}</td>
                    <td>{{ $item->status_peminjaman_222291 }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} on {{ now()->format('d-m-Y H:i:s') }}</p>
    </div>
</body>

</html>
